let defaultCDomain={
"type": "Condensation",
"start": 4,
"end": 302,
"predictions": [],
"napdoslink": "http://napdos.ucsd.edu/cgi-bin/process_request.cgi?query_type=aa&amp;ref_seq_file=all_C_public_12062011.faa&amp;Sequence=%3EC_domain_from_antiSMASH%0DFYPLTNAQKRIWYTEKFYPNTSISNLAGFGKLISEDGVQAHYVEKAIQEFVRRYESMRIRLRLDDEGEPVQYVSEYRPLSIGHTDIRQAGCSADELSKWGREEAGKPLALYDQDLFRFSVHTISENEVWFYANVHHIISDGISMTILGNAITDIYLELSGGTSEEQTEIPSFIEHVLTEQEYVQSKRFKKDRDFWNGQFETVPELVSLKRSQADAGLDAKRFSQEIPHDLYGRIHSFCEEHKVSVLSLFQSALITYLYKVTGRDDVVTGTFMGNRTNAKEKQMLGMFVSTVPVRTSVD",
"blastlink": "http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&amp;PROGRAM=blastp&amp;BLAST_PROGRAMS=blastp&amp;QUERY=FYPLTNAQKRIWYTEKFYPNTSISNLAGFGKLISEDGVQAHYVEKAIQEFVRRYESMRIRLRLDDEGEPVQYVSEYRPLSIGHTDIRQAGCSADELSKWGREEAGKPLALYDQDLFRFSVHTISENEVWFYANVHHIISDGISMTILGNAITDIYLELSGGTSEEQTEIPSFIEHVLTEQEYVQSKRFKKDRDFWNGQFETVPELVSLKRSQADAGLDAKRFSQEIPHDLYGRIHSFCEEHKVSVLSLFQSALITYLYKVTGRDDVVTGTFMGNRTNAKEKQMLGMFVSTVPVRTSVD&amp;LINK_LOC=protein&amp;PAGE_TYPE=BlastSearch",
"sequence": "FYPLTNAQKRIWYTEKFYPNTSISNLAGFGKLISEDGVQAHYVEKAIQEFVRRYESMRIRLRLDDEGEPVQYVSEYRPLSIGHTDIRQAGCSADELSKWGREEAGKPLALYDQDLFRFSVHTISENEVWFYANVHHIISDGISMTILGNAITDIYLELSGGTSEEQTEIPSFIEHVLTEQEYVQSKRFKKDRDFWNGQFETVPELVSLKRSQADAGLDAKRFSQEIPHDLYGRIHSFCEEHKVSVLSLFQSALITYLYKVTGRDDVVTGTFMGNRTNAKEKQMLGMFVSTVPVRTSVD",
"dna_sequence": "ATG",
"abbreviation": "C",
"html_class": "jsdomain-condensation",
"identifier":nameWildcardModule+"_C" ,
"domainOptions": [],
"default_option": [],
"selected_option": [],
"ko": false,
"module": nameWildcardModule,
"function": "C"
}
let defaultADomain={
"type": "AMP-binding",
"start": 465,
"end": 867,
"predictions": [
  [
    "consensus",
    Object.keys(aminoacids).find(key => aminoacids[key] === wildcardSubstrate)

  ]
],
"napdoslink": "",
"blastlink": "http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&amp;PROGRAM=blastp&amp;BLAST_PROGRAMS=blastp&amp;QUERY=FEEKVKSLSDKPAVVYEGRTLSYRTLHEQSGRIAGRLLQAGISADSPVAVLLGRSERVIAAILGILKAGGAYVPIDPDFPADRIQYILEDSGAKAVLTEAGIQAPAADAERIDFNEAVQYETAADGVSTQSDRLAYIIYTSGTTGRPKGVMIEHRQVHHLVQSLQQEIYQCGEQTLRMALLAPFHFDASVKQIFASLLLGQTLYIVPKTTVTNGSALLDYYRQNRIEATDGTPAHLQMMVAAGDVSGIELRHMLIGGEGLSAAVAEQLMTLFHQSGRTPRLTNVYGPTETCVDASVHQMSADNGMNQQAAYVPIGKPLGNARLYILDKHQRLQPDGTAGELYIAGDGVGRGYLNLPDLTAEKFLQDPFNGNGRMYRTGDMARWLPDGTIEYIGREDDQVKVR&amp;LINK_LOC=protein&amp;PAGE_TYPE=BlastSearch",
"sequence": "FEE",
"dna_sequence": "ATGGTCATTCTCTCGAATTTCATGAAAGAACCATTCAATCGTTCAGTGACAGCTTTAAAGGGCACCTCTTGAAAATCATAGATCACTGCCTGGCCCAAGACGGACCTGAGCTTACGCCTAGCGATCTTGGCGATGATGATCTGACGCTTGATGAACTTGATAAATTAATGGAAATTCTCTAA",
"abbreviation": "A",
"html_class": "jsdomain-adenylation",
"identifier": nameWildcardModule+"_A",
"domainOptions": [
  "arginine",
  "histidine",
  "lysine",
  "asparticacid",
  "glutamicacid",
  "serine",
  "threonine",
  "asparagine",
  "glutamine",
  "cysteine",
  "selenocysteine",
  "glycine",
  "proline",
  "alanine",
  "valine",
  "isoleucine",
  "leucine",
  "methionine",
  "phenylalanine",
  "tyrosine",
  "tryptophan"
],
"default_option":wildcardSubstrate,
"selected_option": [],
"ko": false,
"module": nameWildcardModule,
"function": "A",
"substrate": "glutamicacid"
}
let defaultPCPDomain={
"type": "PCP",
  "abbreviation": "PCP",
"start": 976,
"end": 1045,
"predictions": [],
"napdoslink": "",
"blastlink": "http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&amp;PROGRAM=blastp&amp;BLAST_PROGRAMS=blastp&amp;QUERY=EETLAVIWQEVLGMDKAGIYDHFFESGGHSLKAMTLLTKIHKQMGVEIPLQYLFEHPTIAALADYAENR&amp;LINK_LOC=protein&amp;PAGE_TYPE=BlastSearch",
"sequence": "E",
"dna_sequence": "ATG",
"html_class": "jsdomain-transport",
"identifier": nameWildcardModule+"_PCP",
"domainOptions": [],
"default_option": [],
"selected_option": [],
"ko": false,
"module": nameWildcardModule,
"function": "PCP"
}
let defaultACPDomain={
"type": "ACP",
  "abbreviation": "ACP",
"start": 976,
"end": 1045,
"predictions": [],
"napdoslink": "",
"blastlink": "http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&amp;PROGRAM=blastp&amp;BLAST_PROGRAMS=blastp&amp;QUERY=EETLAVIWQEVLGMDKAGIYDHFFESGGHSLKAMTLLTKIHKQMGVEIPLQYLFEHPTIAALADYAENR&amp;LINK_LOC=protein&amp;PAGE_TYPE=BlastSearch",
"sequence": "E",
"dna_sequence": "ATG",
"html_class": "jsdomain-transport",
"identifier": nameWildcardModule+"_ACP",
"domainOptions": [],
"default_option": [],
"selected_option": [],
"ko": false,
"module": nameWildcardModule,
"function": "ACP"
}
let defaultTEDomain={
"type": "Thioesterase",
"start": 1059,
"end": 1254,
"predictions": [],
"napdoslink": "",
"blastlink": "http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&amp;PROGRAM=blastp&amp;BLAST_PROGRAMS=blastp&amp;QUERY=TLFAFPPVLGYGLMYQPLAKQLSGYKICAFDFIEEDNRIERYTELINQLQPEGPVKLFGYSAGCTLAFETAKRLEAGGREVERLIMVDSYKKQGVSDLEGRTVESDVQALMKVNRDNEALNNEAVKEGLAKKTNAFYSYFVHTVSTGRVNADIDLLTSEPDFAMPPWLASWEEATTGEYRVKKGCGTHAEMLQGE&amp;LINK_LOC=protein&amp;PAGE_TYPE=BlastSearch",
"sequence": "TLFAFPPVLGYGLMYQPLAKQLSGYKICAFDFIEEDNRIERYTELINQLQPEGPVKLFGYSAGCTLAFETAKRLEAGGREVERLIMVDSYKKQGVSDLEGRTVESDVQALMKVNRDNEALNNEAVKEGLAKKTNAFYSYFVHTVSTGRVNADIDLLTSEPDFAMPPWLASWEEATTGEYRVKKGCGTHAEMLQGE",
"dna_sequence": "",
"abbreviation": "TE",
"html_class": "jsdomain-terminal",
"identifier": nameWildcardModule+"_TE",
"domainOptions": [
  "O_131",
  "O_4",
  "O_61",
  "N_125",
  "Linear product"
],
"default_option": [
  "Linear product"
],
"selected_option": [],
"ko": false,
"module": nameWildcardModule,
"function": "TE",

}
let defaultEDomain={
"type": "Epimerization",
"start": 3122,
"end": 3421,
"predictions": [],
"napdoslink": "",
"blastlink": "http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&amp;PROGRAM=blastp&amp;BLAST_PROGRAMS=blastp&amp;QUERY=EGEAALTPIQRWFFEKNFTDKHHWNQSVMLHAKDGFDPEITEKTLHVLTVHHDALRMIYREQKPYYRGLEDASVELNVFELNGPAEDHEDRIEREADRLQSSISLETGHLLKAGLFRAEDGDHLLLAIHHLVVDGVSWRILLEDFTSVYTQLKQGNEPALPPKTHSFAEFAERIKEYANTKAFLKEADYWRELEEKEVCTQLPKDRQSGDQRMRHTRTVSFSLTPEQTEQLTTNVHEAYHTEMNDILLTALGLALKEWTGEDTIGVHLEGHGREDILDGLNITRTVGWFTSMYPMILEM&amp;LINK_LOC=protein&amp;PAGE_TYPE=BlastSearch",
"sequence": "EGEAALTPIQRWFFEKNFTDKHHWNQSVMLHAKDGFDPEITEKTLHVLTVHHDALRMIYREQKPYYRGLEDASVELNVFELNGPAEDHEDRIEREADRLQSSISLETGHLLKAGLFRAEDGDHLLLAIHHLVVDGVSWRILLEDFTSVYTQLKQGNEPALPPKTHSFAEFAERIKEYANTKAFLKEADYWRELEEKEVCTQLPKDRQSGDQRMRHTRTVSFSLTPEQTEQLTTNVHEAYHTEMNDILLTALGLALKEWTGEDTIGVHLEGHGREDILDGLNITRTVGWFTSMYPMILEM",
"dna_sequence": "",
  "abbreviation": "E",
"html_class": "jsdomain-epimerase",
"identifier": nameWildcardModule+"_E",
"domainOptions": [],
"default_option": [],
"selected_option": [],
"ko": false,
"module": nameWildcardModule,
"function": "E"
}
let defaultERDomain={
"type": "Enoylreductase",
"start": 3122,
"end": 3421,
"predictions": [],
"napdoslink": "",
"blastlink": "http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&amp;PROGRAM=blastp&amp;BLAST_PROGRAMS=blastp&amp;QUERY=EGEAALTPIQRWFFEKNFTDKHHWNQSVMLHAKDGFDPEITEKTLHVLTVHHDALRMIYREQKPYYRGLEDASVELNVFELNGPAEDHEDRIEREADRLQSSISLETGHLLKAGLFRAEDGDHLLLAIHHLVVDGVSWRILLEDFTSVYTQLKQGNEPALPPKTHSFAEFAERIKEYANTKAFLKEADYWRELEEKEVCTQLPKDRQSGDQRMRHTRTVSFSLTPEQTEQLTTNVHEAYHTEMNDILLTALGLALKEWTGEDTIGVHLEGHGREDILDGLNITRTVGWFTSMYPMILEM&amp;LINK_LOC=protein&amp;PAGE_TYPE=BlastSearch",
"sequence": "EGEAALTPIQRWFFEKNFTDKHHWNQSVMLHAKDGFDPEITEKTLHVLTVHHDALRMIYREQKPYYRGLEDASVELNVFELNGPAEDHEDRIEREADRLQSSISLETGHLLKAGLFRAEDGDHLLLAIHHLVVDGVSWRILLEDFTSVYTQLKQGNEPALPPKTHSFAEFAERIKEYANTKAFLKEADYWRELEEKEVCTQLPKDRQSGDQRMRHTRTVSFSLTPEQTEQLTTNVHEAYHTEMNDILLTALGLALKEWTGEDTIGVHLEGHGREDILDGLNITRTVGWFTSMYPMILEM",
"dna_sequence": "",
  "abbreviation": "ER",
"html_class": "jsdomain-epimerase",
"identifier": nameWildcardModule+"_ER",
"domainOptions": [],
"default_option": [],
"selected_option": [],
"ko": false,
"module": nameWildcardModule,
"function": "ER"
}
let defaultKRDomain={
  "type": "PKS_KR",
  "start": 3110,
  "end": 3287,
  "predictions": [
    [
      "KR activity",
      "active"
    ],
    [
    ]
  ],
  "napdoslink": "",
  "blastlink": "http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&amp;PROGRAM=blastp&amp;BLAST_PROGRAMS=blastp&amp;QUERY=GTILVTGGTAGLGAEVARWLAGRGAEHLALVSRRGPDTEGVGDLTAELTRLGARVSVHACDVSSREPVRELVHGLIEQGDVVRGVVHAAGLPQQVAINDMDEAAFDEVVAAKAGGAVHLDELCSDAELFLLFSSGAGVWGSARQGAYAAGNAFLDAFARHRRGRGLPATSVAWGLWA&amp;LINK_LOC=protein&amp;PAGE_TYPE=BlastSearch",
  "sequence": "G",
  "dna_sequence": "GTG",
  "abbreviation": "KR",
  "html_class": "jsdomain-mod-kr",
  "identifier": nameWildcardModule+"_KR",
  "domainOptions": [
    "A1",
    "A2",
    "B1",
    "B2",
    "C1",
    "C2"
  ],
  "default_option": "A1",
  "selected_option": [],
  "ko": true,
  "module": nameWildcardModule,
  "function": "KR"
}
let defaultATDomain={
  "type": "PKS_AT",
  "start": 110,
  "end": 404,
  "predictions": [
    [
      "consensus",
      "pk"
    ],
    [
      "PKS signature",
      "Malonyl-CoA"
    ],
    [
      "Minowa",
      "prop"
    ]
  ],
  "napdoslink": "",
  "blastlink": "http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&amp;PROGRAM=blastp&amp;BLAST_PROGRAMS=blastp&amp;QUERY=VFPGQGAQWAGMAGELLGESRVFAAAMDACARAFEPVTDWTLAQVLDSPEQSRRVEVVQPALFAVQTSLAALWRSFGVTPDAVVGHSIGELAAAHVCGAAGAADAARAAALWSREMIPLVGNGDMAAVALSADEIEPRIARWDDDVVLAGVNGPRSVLLTGSPEPVARRVQELSAEGVRAQVINVSMAAHSAQVDDIAEGMRSALAWFAPGGSEVPFYASLTGGAVDTRELVADYWRRSFRLPVRFDEAIRSALEVGPGTFVEASPHPVLAAALQQTLDAEGSSAAVVPTLQRG&amp;LINK_LOC=protein&amp;PAGE_TYPE=BlastSearch",
  "sequence": "V",
  "dna_sequence": "GTG",
  "abbreviation": "AT",
  "html_class": "jsdomain-acyltransferase",
  "identifier":  nameWildcardModule+"_AT",
  "domainOptions": [
    "methylmalonylcoa",
    "propionylcoa",
    "malonylcoa"
  ],
  "default_option": "malonylcoa",
  "selected_option": [],
  "ko": false,
  "module":  nameWildcardModule,
  "function": "AT",
  "substrate": "propionylcoa"
}
let defaultKSDomain={
  "type": "PKS_KS(Modular-KS)",
  "start": 559,
  "end": 983,
  "predictions": [],
  "napdoslink": "http://napdos.ucsd.edu/cgi-bin/process_request.cgi?query_type=aa&amp;ref_seq_file=all_KS_public_12062011.faa&amp;Sequence=%3EKS_domain_from_antiSMASH%0DVAVVAMACRLPGGVSTPEEFWELLSEGRDAVAGLPTDRGWDLDSLFHPDPTRSGTAHQRGGGFLTEATAFDPAFFGMSPREALAVDPQQRLMLELSWEVLERAGIPPTSLQASPTGVFVGLIPQEYGPRLAEGGEGVEGYLMTGTTTSVASGRIAYTLGLEGPAISVDTACSSSLVAVHLACQSLRRGESSLAMAGGVTVMPTPGMLVDFSRMNSLAPDGRCKAFSAGANGFGMAEGAGMLLLERLSDARRNGHPVLAVLRGTAVNSDGASNGLSAPNGRAQVRVIQQALAESGLGPADIDAVEAHGTGTRLGDPIEARALFEAYGRDREQPLHLGSVKSNLGHTQAAAGVAGVIKMVLAMRAGTLPRTLHASERSKEIDWSSGAISLLDEPEPWPAGARPRRAGVSSFGISGTNAHAIIEEAP",
  "blastlink": "http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&amp;PROGRAM=blastp&amp;BLAST_PROGRAMS=blastp&amp;QUERY=VAVVAMACRLPGGVSTPEEFWELLSEGRDAVAGLPTDRGWDLDSLFHPDPTRSGTAHQRGGGFLTEATAFDPAFFGMSPREALAVDPQQRLMLELSWEVLERAGIPPTSLQASPTGVFVGLIPQEYGPRLAEGGEGVEGYLMTGTTTSVASGRIAYTLGLEGPAISVDTACSSSLVAVHLACQSLRRGESSLAMAGGVTVMPTPGMLVDFSRMNSLAPDGRCKAFSAGANGFGMAEGAGMLLLERLSDARRNGHPVLAVLRGTAVNSDGASNGLSAPNGRAQVRVIQQALAESGLGPADIDAVEAHGTGTRLGDPIEARALFEAYGRDREQPLHLGSVKSNLGHTQAAAGVAGVIKMVLAMRAGTLPRTLHASERSKEIDWSSGAISLLDEPEPWPAGARPRRAGVSSFGISGTNAHAIIEEAP&amp;LINK_LOC=protein&amp;PAGE_TYPE=BlastSearch",
  "sequence": "P",
  "dna_sequence": "GTG",
  "abbreviation": "KS",
  "html_class": "jsdomain-ketosynthase",
  "identifier":  nameWildcardModule+"_KS",
  "domainOptions": [],
  "default_option": [],
  "selected_option": [],
  "ko": false,
  "module": nameWildcardModule,
  "function": "KS"
}
let defaultDHDomain={
  "type": "PKS_DH",
  "start": 2376,
  "end": 2540,
  "predictions": [],
  "napdoslink": "",
  "blastlink": "http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins&amp;PROGRAM=blastp&amp;BLAST_PROGRAMS=blastp&amp;QUERY=HPLLLAAVDVPGHGGAVFTGRLSTDEQPWLAEHVVGGRTLVPGSVLVDLALAAGEDVGLPVLEELVLQRPLVLAGAGALLRMSVGAPDESGRRTIDVHAAEDVADLADAQWSQHATGTLAQGVAAGPRDTEQWPPEDAVRIPLDDHYDGLAEQGYEYGPSFQAL&amp;LINK_LOC=protein&amp;PAGE_TYPE=BlastSearch",
  "sequence": "HPLLLAAVDVPGHGGAVFTGRLSTDEQPWLAEHVVGGRTLVPGSVLVDLALAAGEDVGLPVLEELVLQRPLVLAGAGALLRMSVGAPDESGRRTIDVHAAEDVADLADAQWSQHATGTLAQGVAAGPRDTEQWPPEDAVRIPLDDHYDGLAEQGYEYGPSFQAL",
  "dna_sequence": "GTGACTGACAGCGAGAAGGTGGCGGAGTACCTCCGTCGGGCGACGCTCGACCTGCGTGCCGCCCGGCAGCGCATCCGCGAGCTGGAATCCGACCCGATCGCCATCGTCAGCATGGCCTGCCGCCTGCCGGGCGGGGTGAACACCCCGCAGCGGCTGTGGGAGCTGCTGCGCGAGGGCGGTGAGACGCTGTCGGGCTTCCCCACCGACCGGGGCTGGGACCTGGCGCGGCTGCACCACCCCGACCCGGACAACCCCGGTACCAGCTACGTCGACAAGGGCGGGTTCCTCGACGACGCGGCGGGCTTCGACGCGGAGTTCTTCGGCGTCTCGCCGCGCGAGGCCGCGGCCATGGACCCGCAGCAGCGGCTGCTGCTGGAGACGAGCTGGGAGCTGGTGGAGAACGCCGGCATCGACCCGCACTCGCTGCGCGGTACCGCGACCGGCGTCTTCCTCGGAGTGGCGAAGTTCGGCTACGGCGAGGACACCGCCGCGGCGGAGGACGTCGAGGGCTACTCGGTCACCGGTGTGGCGCCCGCGGTCGCCTCCGGCCGCATCTCCTACACCATGGGCCTGGAGGGGCCGTCGATCAGCGTCGACACCGCGTGCTCGTCGTCGCTGGTGGCGCTGCACCTGGCGGTCGAGTCGCTGCGCAAGGGCGAGTCGTCGATGGCGGTCGTCGGCGGTGCCGCGGTGATGGCGACCCCGGGGGTGTTCGTCGACTTCAGCCGGCAGCGCGCGCTCGCCGCCGACGGGCGGTCGAAGGCGTTCGGTGCCGGCGCCGACGGGTTCGGCTTCTCCGAAGGCGTCACCCTGGTCCTGCTCGAGCGGCTGTCGGAGGCGCGGCGAAACGGGCACGAGGTGCTGGCGGTGGTTCGCGGCTCGGCGCTCAACCAGGACGGGGCCAGCAACGGGCTTTCCGCGCCGAGCGGGCCCGCGCAGCGCAGGGTCATCCGGCAGGCCCTCGAGAGCTGCGGTCTGGAGCCCGGCGACGTCGACGCGGTGGAGGCGCACGGCACCGGTACGGCGCTCGGCGACCCGATCGAGGCGAACGCGCTGCTGGACACCTACGGCCGCGACCGCGACGCCGACCGGCCGCTCTGGCTGGGCTCGGTGAAGTCCAACATCGGCCACACCCAGGCGGCAGCGGGCGTCACCGGCCTGCTGAAGGTGGTCCTGGCGCTGCGCAACGGGGAACTGCCCGCGACCCTGCACGTCGAGGAGCCCACGCCGCACGTCGACTGGTCGTCCGGCGGCGTGGCGCTGCTGGCGGGCAACCAGCCGTGGCGGCGCGGCGAGCGGACTCGGCGCGCCGCTGTTTCCGCGTTCGGGATCAGCGGGACGAATGCGCACGTGATCGTCGAGGAAGCTCCTGAGCGCGAGCACCGGGAGACCACCGCGCACGACGGCCGACCGGTTCCGCTGGTGGTGTCCGCGCGCAGCACGGCGGCGTTGCGGGCGCAGGCCGCCCAGATCGCCGAGCTGCTCGAACGCCCGGACGCCGACCTCGCCGGGGTCGGGCTGGGCCTGGCCACGACCCGCGCCCGCCACGAGCACCGCGCCGCCGTGGTGGCATCGACCCGCGAGGAAGCGGTGCGCGGACTGCGGGAGATCGCCGCCGGTGCCGCGACGGCCGACGCCGTGGTCGAGGGCGTCACCGAGGTGGACGGGCGCAACGTCGTCTTCCTGTTCCCGGGGCAGGGTTCGCAATGGGCCGGCATGGGTGCCGAGCTGCTGTCGTCGTCGCCGGTGTTCGCCGGGAAGATCCGGGCCTGCGACGAGTCGATGGCCCCGATGCAGGACTGGAAGGTCTCCGACGTGCTGCGTCAGGCGCCGGGGGCGCCGGGCCTGGACCGGGTCGACGTGGTGCAGCCGGTGTTGTTCGCGGTGATGGTGTCGCTGGCGGAGCTGTGGCGCTCGTACGGCGTGGAGCCCGCGGCGGTCGTGGGGCACTCGCAGGGCGAGATCGCCGCCGCGCACGTCGCCGGGGCGCTCACGTTGGAGGACGCGGCGAAGCTCGTCGTGGGCCGCAGCCGCCTGATGCGGTCGCTCTCCGGGGAGGGCGGCATGGCCGCCGTCGCGCTGGGCGAGGCCGCGGTGCGCGAGCGCCTGCGGCCGTGGCAGGACCGGCTCTCGGTGGCCGCGGTCAACGGTCCCCGGTCGGTCGTGGTCTCCGGCGAGCCCGGCGCGCTGCGGGCGTTTTCCGAGGACTGCGCGGCCGAGGGCATCCGCGTCCGCGACATCGACGTGGACTACGCCTCGCACTCGCCGCAGATCGAGCGGGTCCGCGAGGAACTCCTCGAAACGACCGGCGACATCGCGCCGCGCCCGGCGCGGGTGACGTTCCACTCCACTGTGGAGTCGCGGTCTATGGACGGCACCGAGCTGGATGCCCGGTACTGGTACCGCAACCTGCGCGAGACGGTGCGCTTCGCCGACGCCGTGACGCGGCTGGCGGAGTCGGGATACGACGCGTTCATCGAGGTCAGCCCGCATCCGGTCGTGGTCCAGGCCGTCGAGGAGGCGGTCGAAGAGGCTGACGGTGCCGAAGACGCGGTCGTAGTCGGCTCGCTGCACCGCGACGGCGGTGACCTCTCGGCCTTCCTGCGGTCGATGGCCACCGCGCACGTGTCCGGTGTGGACATCAGGTGGGACGTCGCTCTGCCCGGCGCCGCGCCCTTCGCGCTGCCGACGTATCCGTTCCAGCGCAAGCGCTACTGGCTCCAGCCCGCCGCACCCGCCGCCGCCTCCGACGAGCTGGCCTACCGCGTTTCCTGGACTCCGATCGAAAAGCCGGAGTCGGGAAACCTGGACGGCGACTGGTTGGTTGTCACACCCCTCATCAGTCCGGAGTGGACGGAAATGCTGTGCGAGGCCATCAACGCCAACGGTGGCAGGGCGTTGCGCTGCGAGGTGGACACGTCCGCTTCGCGCACTGAGATGGCCCAGGCCGTCGCACAGGCCGGAACGGGATTCCGGGGCGTGCTCTCGTTGCTGTCGTCGGACGAATCCGCCTGCCGTCCGGGGGTTCCTGCCGGTGCGGTCGGCCTGCTCACCCTGGTCCAGGCGCTGGGCGATGCCGGGGTCGACGCACCGGTGTGGTGCCTGACCCAGGGTGCGGTCCGCACTCCCGCCGACGACGACCTCGCCCGGCCTGCGCAGACCACCGCGCACGGCTTCGCGCAGGTCGCCGGGCTGGAGCTGCCGGGCCGCTGGGGCGGTGTGGTCGACCTGCCCGAATCGGTCGACGACGCGGCGCTGCGTCTGCTCGTGGCAGTCCTGCGCGGCGGCGGCCGTGCCGAGGACCACCTCGCGGTCCGGGACGGCCGCCTCCACGGCCGTCGCGTCGTCCGCGCAAGCCTGCCGCAGTCCGGCTCGCGGAGCTGGACCCCGCACGGGACCGTGCTGGTCACCGGCGCGGCGAGCCCCGTCGGCGACCAACTGGTGCGGTGGCTCGCCGACCGGGGAGCCGAGCGGCTGGTGCTGGCCGGAGCCTGTCCGGGCGACGACCTGCTGGCCGCGGTCGAGGAAGCGGGCGCATCGGCCGTCGTGTGCGCCCAGGACGCGGCGGCGCTGCGCGAGGCGCTCGGCGACGAGCCGGTGACCGCGCTCGTGCACGCCGGAACCCTGACGAACTTCGGCAGCATCAGCGAAGTCGCACCGGAGGAGTTCGCCGAGACGATCGCGGCCAAGACCGCGTTGCTCGCCGTGCTGGACGAAGTCCTCGGCGACCGGGCCGTCGAGCGGGAGGTCTACTGCTCGTCGGTCGCCGGGATCTGGGGCGGCGCCGGGATGGCCGCCTACGCGGCAGGCAGCGCCTACCTCGACGCGCTGGCCGAGCACCACCGCGCGCGGGGCCGCTCGTGCACCTCGGTCGCCTGGACGCCGTGGGCGCTGCCGGGCGGGGCGGTGGACGACGGCTACCTGCGGGAACGCGGACTGCGCAGCCTCTCCGCCGACAGGGCGATGCGCACCTGGGAGCGGGTGCTGGCCGCCGGGCCGGTGTCGGTCGCGGTGGCCGACGTGGACTGGCCGGTGCTCAGCGAAGGCTTCGCCGCCACCCGGCCGACCGCGCTGTTCGCCGAACTCGCCGGCCGCGGCGGACAGGCGGAGGCCGAGCCGGACAGCGGACCGACCGGCGAGCCGGCACAACGGCTCGCGGGGCTTTCCCCGGACGAGCAGCAGGAAAACCTGCTCGAACTCGTCGCGAACGCGGTTGCCGAGGTGCTTGGCCACGAGTCCGCCGCCGAGATCAACGTGCGCCGCGCGTTCAGCGAGCTCGGACTCGACTCGCTCAACGCGATGGCCCTGCGCAAGCGCCTGTCGGCGAGCACCGGCCTGCGGCTGCCCGCGTCGCTGGTGTTCGACCACCCCACCGTCACCGCGCTCGCGCAGCACCTGCGCGCCCGGCTCGTCGGTGACGCCGACCAGGCCGCGGTGCGCGTCGTCGGCGCGGCCGACGAGTCCGAGCCCATCGCCATCGTCGGCATCGGCTGCCGTTTCCCCGGCGGCATCGGCTCGCCCGAGCAGTTGTGGCGGGTGCTGGCCGAGGGCGCGAACCTCACCACCGGCTTCCCGGCCGACCGGGGCTGGGACATCGGGCGGCTCTACCACCCGGACCCGGACAACCCCGGCACCAGCTACGTGGACAAGGGCGGGTTCCTCACCGACGCGGCGGATTTCGACCCGGGCTTCTTCGGCATCACGCCCCGCGAAGCGCTGGCGATGGACCCGCAGCAGCGCCTCATGCTGGAGACGGCGTGGGAGGCAGTGGAACGCGCGGGCATCGACCCCGACGCCCTGCGAGGCACCGACACCGGCGTCTTCGTCGGCATGAACGGCCAGTCCTACATGCAGCTGCTGGCCGGTGAGGCCGAACGCGTCGACGGCTACCAGGGCCTCGGAAACTCCGCGAGCGTGCTCTCCGGGCGCATCGCCTACACCTTCGGCTGGGAGGGCCCGGCGCTGACGGTGGACACCGCGTGCTCGTCCTCGCTGGTCGGCATCCACCTCGCGATGCAGGCGCTGCGGCGCGGTGAGTGCTCCCTGGCGCTGGCCGGCGGCGTCACGGTCATGTCCGACCCGTACACCTTCGTCGACTTCAGCACGCAGCGCGGGCTCGCCTCCGACGGTCGCTGCAAGGCGTTCTCCGCGCGGGCCGACGGCTTCGCGCTGTCGGAAGGCGTCGCCGCGCTGGTGCTGGAGCCGCTTTCCCGGGCGCGCGCCAACGGGCACCAGGTGCTGGCCGTGCTGCGCGGCAGCGCGGTCAACCAGGACGGTGCCAGCAACGGTCTCGCCGCTCCCAACGGCCCGTCGCAGGAGCGGGTGATCCGGCAGGCGCTCGCCGCTTCGGGCGTGCCGGCCGCGGACGTCGACGTCGTGGAGGCGCACGGGACGGGCACCGAGCTCGGCGACCCGATCGAGGCCGGCGCGCTCATCGCGACCTACGGCCAGGACCGCGACCGGCCGCTGCGGCTCGGCTCGGTGAAGACCAACATCGGCCACACCCAGGCCGCGGCGGGCGCCGCGGGCGTGATCAAGGTCGTGCTGGCGATGCGGCACGGGATGCTGCCCCGGTCGTTGCACGCCGACGAGCTGTCCCCGCACATCGACTGGGAGTCGGGGGCCGTGGAGGTGCTGCGCGAGGAGGTGCCGTGGCCGGCGGGTGAGCGCCCCCGGCGGGCGGGGGTGTCGTCCTTCGGCGTCAGCGGAACCAACGCGCACGTGATCGTCGAAGAGGCACCAGCAGAGCAGGAGGCCGCCCGCACCGAGCGCGGTCCGCTGCCGTTCGTGCTGTCCGGCCGCAGCGAAGCCGTGGTCGCGGCCCAGGCCCGCGCGCTCGCCGAGCACCTGCGCGACACCCCGGAGCTCGGCCTGACCGACGCGGCGTGGACGCTCGCGACCGGCAGGGCGCGGTTCGACGTGCGAGCCGCCGTGCTCGGCGACGACCGCGCGGGCGTGTGCGCGGAGCTGGACGCGCTGGCCGAGGGCCGCCCGTCGGCCGACGCCGTCGCGCCGGTGACCTCCGCGCCGCGCAAGCCGGTCCTGGTCTTCCCCGGCCAGGGCGCGCAGTGGGTCGGCATGGCACGCGATCTGCTGGAATCCTCCGAGGTGTTCGCCGAGTCGATGAGCCGGTGCGCCGAGGCGCTCTCGCCGCACACCGACTGGAAGTTGCTCGACGTCGTCCGCGGCGACGGCGGTCCCGACCCGCACGAGCGCGTCGACGTGCTCCAGCCGGTGCTCTTCTCGATCATGGTCTCGCTGGCCGAGCTGTGGCGCGCGCACGGCGTGACCCCGGCCGCCGTCGTCGGCCACTCGCAGGGCGAGATCGCCGCGGCGCACGTGGCGGGCGCGCTGTCGCTGGAAGCCGCCGCGAAGGTGGTGGCCCTGCGCAGCCAGGTGTTGCGCGAGCTCGACGACCAGGGCGGCATGGTGTCGGTCGGCGCGTCCCGCGACGAGCTGGAGACCGTGCTCGCGCGCTGGGACGGCCGTGTCGCGGTGGCCGCCGTGAACGGGCCTGGCACCAGCGTCGTTGCCGGGCCGACCGCGGAGCTGGACGAGTTCTTCGCCGAGGCCGAGGCGCGGGAGATGAAGCCGCGCCGGATCGCCGTGCGCTACGCCTCCCACTCCCCGGAGGTGGCGCGCATCGAGGACCGGCTCGCGGCCGAGCTGGGCACCATCACCGCCGTGCGGGGCTCGGTGCCGCTGCACTCCACGGTGACCGGCGAGGTCATCGACACCTCCGCGATGGACGCCTCCTACTGGTACCGCAACCTGCGCCGACCAGTGCTCTTCGAGCAGGCGGTGCGCGGTCTGGTCGAGCAGGGCTTCGACACCTTCGTCGAGGTGAGCCCGCACCCGGTGCTGCTGATGGCGGTCGAGGAGACCGCCGAGCACGCGGGCGCGGAAGTCACCTGCGTGCCGACGCTGCGCCGCGAGCAGAGCGGACCGCACGAGTTCCTGCGCAACCTGCTGCGGGCTCACGTGCACGGCGTCGGCGCCGACCTGCGTCCGGCGGTGGCCGGGGGACGGCCGGCCGAGCTGCCCACCTACCCGTTCGAACACCAGCGCTTCTGGCCGCGGCCGCACCGGCCCGCCGACGTCTCGGCGCTGGGCGTGCGCGGCGCGGAGCACCCGCTGCTGCTCGCCGCGGTCGACGTGCCGGGCCACGGCGGTGCGGTGTTCACCGGAAGGCTTTCCACCGACGAGCAGCCGTGGCTGGCCGAACACGTCGTGGGCGGCCGGACGCTGGTGCCGGGCAGCGTCCTGGTCGATCTCGCGCTCGCCGCGGGTGAGGACGTCGGGCTGCCGGTCCTGGAGGAACTGGTGTTGCAACGGCCGCTGGTGCTGGCCGGGGCGGGGGCGCTGCTGCGCATGTCGGTCGGCGCGCCCGACGAGTCGGGGCGGCGGACGATCGACGTCCACGCCGCCGAAGACGTGGCCGACCTCGCCGACGCGCAGTGGTCGCAGCACGCCACCGGGACGCTCGCGCAGGGCGTCGCCGCGGGTCCGAGGGATACCGAGCAGTGGCCGCCGGAGGACGCCGTCCGCATCCCGCTCGACGACCACTACGACGGCCTCGCCGAGCAGGGCTACGAGTACGGACCGTCGTTCCAGGCCCTGCGAGCCGCGTGGCGCAAGGACGACTCGGTCTACGCCGAGGTGTCCATCGCGGCGGACGAGGAAGGTTACGCGTTCCACCCGGTGCTGCTCGACGCCGTGGCGCAGACGCTCAGCCTGGGCGCCCTCGGCGAGCCGGGCGGGGGAAAGCTGCCGTTCGCGTGGAACACCGTGACCCTGCACGCCTCCGGGGCGACCTCGGTGCGGGTCGTGGCGACGCCCGCCGGGGCGGACGCGATGGCCCTGCGGGTCACCGACCCGGCAGGCCACCTGGTCGCCACGGTCGACTCGCTGGTCGTCCGCAGCACCGGGGAGAAGTGGGAGCAGCCCGAACCGCGCGGTGGCGAGGGCGAGCTGCACGCTCTGGACTGGGTACGGCTAGCCGAGCCCGGCTCGACCGGTCGTGTGGTCGCGGCCGATGCCTCGGACCTCGACGCCGTCCTGCGGTCCGGTGAACCCGAACCCGACGCGGTCCTGGTCCGCTACGAACCCGAAGGCGACGACCCCCGCGCCGCGGCCCGCCACGGCGTCCTCTGGGCCGCCGCGCTCGTGCGCCGCTGGCTCGAACAGGAGGAGCTGCCGGGCGCGACGCTGGTCATCGCCACGTCCGGCGCGGTCACCGTGTCCGACGACGACAGCGTTCCCGAACCCGGCGCCGCCGCGATGTGGGGCGTGATCCGCTGTGCGCAGGCCGAGTCGCCGGACCGGTTCGTGCTCCTCGACACCGACGCGGAACCTGGGATGCTGCCTGCGGTTCCGGACAACCCGCAGCTCGCGTTGCGCGGCGACGACGTCTTCGTGCCGCGCCTCTCGCCGCTCGCACCTTCCGCGCTGACGCTTCCGGCAGGCACCCAACGTCTCGTGCCGGGTGACGGGGCGATCGACTCCGTGGCCTTCGAGCCCGCACCCGACGTCGAGCAGCCGCTCCGGGCGGGCGAGGTCCGGGTGGACGTGCGCGCCACCGGAGTCAACTTCCGCGACGTCCTCCTCGCACTCGGCATGTATCCGCAGAAGGCGGACATGGGCACCGAGGCCGCCGGTGTCGTCACGGCGGTCGGACCGGACGTGGACGCCTTCGCGCCGGGAGACCGGGTGCTCGGCCTGTTCCAGGGAGCCTTCGCGCCGATCGCGGTCACCGATCACCGGCTCCTCGCACGAGTGCCGGACGGCTGGAGCGACGCCGACGCCGCGGCCGTGCCCATCGCCTACACCACGGCGCATTACGCGCTGCACGATCTCGCGGGGCTGCGCGCGGGTCAGTCGGTGCTCATCCACGCAGCGGCAGGCGGTGTCGGCATGGCGGCCGTCGCGCTGGCCCGCCGAGCGGGGGCGGAGGTGTTGGCCACCGCCGGCCCGGCCAAGCACGGGACGCTGCGGGCGCTCGGTCTCGACGACGAGCACATCGCTTCCTCCCGGGAGACCGGTTTCGCCCGGAAGTTCCGGGAGCGCACCGGAGGCCGCGGCGTGGACGTGGTGCTCAACTCGCTCACCGGGGAACTGCTCGACGAGTCCGCGGATCTGCTCGCCGAGGACGGCGTCTTCGTCGAGATGGGCAAGACCGACCTGCGGGACGCCGGGGACTTCCGGGGCCGATACGCCCCGTTCGACCTCGGCGAGGCGGGTGACGACCGGCTCGGGGAGATCCTGCGCGAGGTCGTCGGCCTGCTGGGCGCCGGGGAGCTCGACCGGCTCCCGGTATCGGCGTGGGAGCTGGGATCCGCGCCCGCGGCGTTGCAGCACATGAGCCGGGGCAGGCACGTCGGCAAGCTCGTGCTGACCCAGCCCGCGCCGGTGGACCCGGACGGCACGGTGCTGATCACGGGTGGCACCGGCACGCTCGGACGGCTGCTCGCGCGCCACCTCGTCACCGAGCACGGCGTGCGGCACCTGCTGCTGGTCAGCAGGCGCGGCGCGGACGCGCCGGGTTCCGACGAGCTGCGCGCGGAGATCGAGGACTTGGGCGCGTCCGCGGAGATCGCGGCTTGCGACACCGCCGACCGCGACGCGCTTTCGGCGCTGCTGGACGGGCTGCCCCGGCCGCTGACCGGTGTCGTGCACGCGGCGGGTGTGCTGGCCGACGGGCTGGTCACCTCCATCGACGAGCCGGCGGTGGAGCAGGTGCTGCGCGCCAAGGTCGACGCGGCGTGGAACCTGCACGAGCTGACCGCGAACACCGGTCTGAGCTTCTTCGTGCTGTTCTCGTCCGCGGCGTCGGTGCTAGCCGGCCCGGGGCAGGGCGTGTACGCGGCCGCGAACGAGTCGCTCAACGCGCTGGCTGCCCTCCGGAGGACGCGCGGCCTTCCCGCGAAGGCGCTCGGATGGGGACTGTGGGCGCAGGCCAGCGAGATGACCAGCGGACTCGGCGACCGCATCGCCCGGACCGGGGTCGCCGCGCTGCCGACCGAGCGGGCGCTCGCACTGTTCGACAGCGCCCTGCGCCGCGGCGGTGAGGTCGTGTTCCCGCTGTCCATCAACCGTTCCGCGCTGCGCAGGGCCGAGTTCGTGCCGGAGGTCCTGCGCGGCATGGTCAGGGCGAAGCTGCGCGCCGCCGGGCAGGCCGAGGCGGCAGGGCCGAACGTGGTCGACCGGCTCGCCGGTCGGTCCGAGTCCGACCAGGTCGCCGGGCTGGCCGAACTGGTGCGTTCACACGCGGCGGCGGTCTCCGGGTACGGCTCGGCCGACCAGCTCCCCGAGCGCAAGGCGTTCAAGGACCTCGGTTTCGACTCGCTGGCCGCGGTGGAGCTGCGCAACCGCCTCGGTACCGCGACCGGCGTGCGGCTGCCCAGCACGTTGGTGTTCGACCACCCGACTCCGCTGGCGGTGGCCGAACACCTGCGGGACAGGCTGTTCGCGGCCTCACCGGCGGTGGACATCGGCGACCGGCTGGACGAGCTGGAGAAGGCGCTCGAAGCCCTGTCCGCCGAGGACGGGCACGACGACGTGGGCCAGCGCCTGGAGTCGCTGCTGCGCCGGTGGAACAGCAGGCGGGCGGACGCCCCGAGCACGTCCGCGATCAGCGAGGACGCCAGTGACGACGAGCTGTTCTCGATGCTCGACCAGCGGTTCGGCGGGGGAGAGGACCTGTAG",
  "abbreviation": "DH",
  "html_class": "jsdomain-mod-dh",
  "identifier": "SACE_0723_8",
  "domainOptions": [],
  "default_option": [],
  "selected_option": [],
  "ko": false,
  "module": "SACE_0723_1",
  "function": "DH"
}
